AWSTemplateFormatVersion: '2010-09-09'
Resources:

  MySiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ai-interviewer-atelenko
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  MyCloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Access Identity for ai-interviewer

  MyBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MySiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: GrantCloudFrontAccess
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt MyCloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub "${MySiteBucket.Arn}/*"

  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: !GetAtt MySiteBucket.RegionalDomainName
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${MyCloudFrontOAI}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD]
          CachedMethods: [GET, HEAD]
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html
        ViewerCertificate:
          CloudFrontDefaultCertificate: true

Outputs:
  CloudFrontURL:
    Value: !Sub "https://${MyCloudFrontDistribution.DomainName}"