version = 0.1

[default.deploy.parameters]
stack_name = "interviewer-app"
resolve_s3 = true
s3_prefix = "interviewer-app"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
