/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VacanciesRouteImport } from './routes/vacancies'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InterviewVacancySKRouteImport } from './routes/interview.$vacancySK'

const VacanciesRoute = VacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewVacancySKRoute = InterviewVacancySKRouteImport.update({
  id: '/interview/$vacancySK',
  path: '/interview/$vacancySK',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/vacancies': typeof VacanciesRoute
  '/interview/$vacancySK': typeof InterviewVacancySKRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/vacancies': typeof VacanciesRoute
  '/interview/$vacancySK': typeof InterviewVacancySKRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/vacancies': typeof VacanciesRoute
  '/interview/$vacancySK': typeof InterviewVacancySKRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/vacancies' | '/interview/$vacancySK'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/vacancies' | '/interview/$vacancySK'
  id: '__root__' | '/' | '/about' | '/vacancies' | '/interview/$vacancySK'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  VacanciesRoute: typeof VacanciesRoute
  InterviewVacancySKRoute: typeof InterviewVacancySKRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vacancies': {
      id: '/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof VacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview/$vacancySK': {
      id: '/interview/$vacancySK'
      path: '/interview/$vacancySK'
      fullPath: '/interview/$vacancySK'
      preLoaderRoute: typeof InterviewVacancySKRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  VacanciesRoute: VacanciesRoute,
  InterviewVacancySKRoute: InterviewVacancySKRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
